### ISSUE TITLE
npm init fastify --integrate fails with npm v7

### ISSUE THREAD

**Issue by davidmarkclements** [fastify/create-fastify#3]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x.x

### Node.js version

14.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

all

### Description

`npm init fastify --integrate` seems to break with `npm` version 7.

### Steps to Reproduce

run `npm init fastify --integrate` in a folder with a `package.json` using `npm` version 7+

### Expected Behavior

it should initialize a fastify project by extending `package.json`

**Comment by mcollina** [comment]
Thanks Dave! Have you got an idea on how this could be fixed?

**Comment by 0xvbetsun** [comment]
that problem occurs because `npm init ...` has been using `npm exec`, under the hood, since the 7th version of npm. So, it needs to pass parameters like `--integrate` via `--`. And now this functionality is failing because of ignoring additional args.
Probably the easiest solution would be adding that behavior to the documentation as follows:
```sh
// npm 6
npm init fastify --integrate

// npm 7
npm init fastify -- --integrate
```

**Comment by JoffrayBillon** [comment]
Problem is happening also for npm 8, none of `npm init fastify --integrate` and `npm init fastify -- --integrate` works

**Comment by mcollina** [comment]
Could you open a fresh issue? Looks like a different problem.
